version: "3.8"

services:
  maria-db:
    image: mariadb:10.7
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  vme:
    depends_on:
      - maria-db
    build: .
    tty: true
    environment:
      DB_HOST: maria-db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SESSION_KEY: ${SESSION_KEY}
    restart: always
    ports:
      - "3000:3000"
